<article class="article-admin">
    <h2><?=$article->getTitle()?></h2>
    <p><?=nl2br($article->getContent())?></p>
    <img src="<?=$article->getPicture()?>">
    <br>
	<a href="index.php?page=editarticle&id=<?=$article->getId()?>">Editer</a>
    <form method="POST">
        <input type="hidden" name="action" value="delete">
		<input type="hidden" name="id" value="<?=$article->getId()?>">
		<input type="submit" value="Supprimer">
    </form>
</article>