<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	<link rel="stylesheet" type="text/css" href="Public/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="Public/css/style.css">
<script defer src="/static/fontawesome/fa-v4-shims.js"></script>
	
	<title>Sangohan</title>
</head>
<body class="body-user">
<?php
	require('Apps/headeruser.php');
	require('Apps/contentuser.php');
	require('Apps/footeruser.php');
?>

</body>
</html>