<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	
	<link rel="stylesheet" type="text/css" href="public/css/style.css"><link rel="stylesheet" type="text/css" href="public/css/normalize.css">
	
	<title>Sangohan Admin</title>
</head>
<body class="body-admin">
<?php
	if (isset($_SESSION['id'])) {
		require('Apps/headeradmin.php');
		require('Apps/contentadmin.php');
		require('Apps/footeradmin.php');
	}
	else{
		require ('Apps/login.php');
	}
	
?>
</body>
</html>
