<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="Public/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="Public/css/style.css">
	<link rel="stylesheet" type="text/css" href="Public/css/stylek.css">
	<link rel="stylesheet" type="text/css" href="Public/css/stylem.css">
	<link rel="stylesheet" type="text/css" href="Public/css/stylej.css">
	<script type="text/javascript" src="js/jquery-3.3.1.js"></script>
	<title>Sangohan</title>
</head>
<body class="body-user">
<?php
	require('Apps/headeruser.php');
	require('Apps/contentuser.php');
	require('Apps/footeruser.php');
?>
<script type="text/javascript" src="js/main.js"></script>
</body>
</html>