<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	<link rel="stylesheet" type="text/css" href="Public/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="Public/css/style.css">
	<link rel="stylesheet" type="text/css" href="Public/css/stylej.css">
	<link rel="stylesheet" type="text/css" href="Public/css/stylem.css">
	<link rel="stylesheet" type="text/css" href="Public/css/stylek.css">
	
	<title>Sangohan Admin</title>
</head>
<body class="body-admin">
<?php
	if (isset($_SESSION['id'])) {
		require('Apps/headeradmin.php');
		require('Apps/contentadmin.php');
		require('Apps/footeradmin.php');
	}
	else{
		require ('Apps/login.php');
	}
	
?>
</body>
</html>
