<section class="register">
<h2>Création du compte</h2>
	<form method="POST">
		<input type="hidden" name="action" value="register">
			<p><label for="login">Login :</label><input type="text" name="login"></p>
			<p><label for="password">Password :</label><input type="password" name="password"></p>
			<button type="submit">Créer le compte</button>
	</form>
	<form method="POST">
		<?php require('Apps/error.php'); ?>
	</form>
</section>