<section class="create">

    <h3>Création d'article</h3>
    <div>
        <form method="POST">
            <input type="hidden" name="action" value="create">
            <div>
                <p><input style="padding-left:10px" type="text" name="title" placeholder="Titre"></p>
            </div>
            <div>
                <p><textarea name="content" placeholder="Contenu"></textarea></p>
            </div>
            <div>
                <p><input style="padding-left:10px" type="file" name="picture"></p>
            </div>
            <div>
                <p><button type="submit">Créer article</button></p>
                <!-- <p><input class="edition" type="submit" value="Créer Article"></p> -->
            </div>

        </form>
    </div>
</section>
