<section class="create">

    <h3>Création d'article</h3>
    <div>
        <form method="POST">
            <input type="hidden" name="group" value="article">
            <input type="hidden" name="action" value="create">
            <div>
                <p><input style="padding-left:10px" type="text" name="title" placeholder="Titre"></p>
            </div>
            <div>
                <p><textarea name="content" placeholder="Contenu"></textarea></p>
            </div>
            <div>
                <p><input style="padding-left:10px" type="url" name="image" placeholder="URL image"></p>
            </div>
            <div>
                <p><input class="edition" type="submit" value="Créer Article"></p>
    </div>

        </form>
    </div>
</section>
