<section class="delivery">
	<section class="food">
	<h1>A emporter</h1>
			<section class="entre">
    			<h3>Entrées</h3>
	        	<ul class="menu entre">
			    <?php 
			    foreach ($products as $product) {
			        if(($product->getType())=="entre")
			        { 
			    ?>
   				
		            <li>
		                <img src="<?=$product->getPicture()?>">
		            <h5><?=$product->getProductTitle()?></h5>
		            <small><?=$product->getProductDescription()?></small>
		            <section class="price">
		                <p><strong><?=$product->getPrice()?></strong></p>
		            </section>
		            <p>Nombre : <select name="nbProducts[<?=$product->getProductId()?>]" id="select">
							        <option>---</option>
							        <option value="1">1</option>
							        <option value="2">2</option>
							        <option value="3">3</option>
							        <option value="4">4</option>
							        <option value="5">5</option>
							    </select></p>
		            </li>
        		<?php 
        			};
       			}
       			?>
    			</ul>
    		</section>

    		<section class="plat">
    			<h3>Entrées</h3>
	        	<ul class="menu plat">
			    <?php 
			    foreach ($products as $product) {
			        if(($product->getType())=="plat")
			        { 
			    ?>
		            <li>
		                <img src="<?=$product->getPicture()?>">
		            <h5><?=$product->getProductTitle()?></h5>
		            <small><?=$product->getProductDescription()?></small>
		            <section class="price">
		                <p><strong><?=$product->getPrice()?></strong></p>
		            </section>
		            <p>Nombre : <select name="nbProducts[<?=$product->getProductId()?>]">
							        <option>---</option>
							        <option value="1">1</option>
							        <option value="2">2</option>
							        <option value="3">3</option>
							        <option value="4">4</option>
							        <option value="5">5</option>
							    </select></p>
		            </li>
				
        		<?php 
        			};
       			}
       			?>
    			</ul>
    		</section>

    		<section class="dessert">
    			<h3>Entrées</h3>
	        	<ul class="menu dessert">
			    <?php 
			    foreach ($products as $product) {
			        if(($product->getType())=="dessert")
			        { 
			    ?>
   				
		            <li>
		                <img src="<?=$product->getPicture()?>">
		            <h5><?=$product->getProductTitle()?></h5>
		            <small><?=$product->getProductDescription()?></small>
		            <section class="price">
		                <p><strong><?=$product->getPrice()?></strong></p>
		            </section>
		            <p>Nombre : <select name="nbProducts[<?=$product->getProductId()?>]">
							        <option>---</option>
							        <option value="1">1</option>
							        <option value="2">2</option>
							        <option value="3">3</option>
							        <option value="4">4</option>
							        <option value="5">5</option>
							    </select></p>
		            </li>
				
        		<?php 
        			};
       			}
       			?>
    			</ul>
    		</section>

    		<section class="boisson">
    			<h3>Entrées</h3>
	        	<ul class="menu boisson">
			    <?php 
			    foreach ($products as $product) {
			        if(($product->getType())=="boisson")
			        { 
			    ?>
		            <li>
		                <img src="<?=$product->getPicture()?>">
		            <h5><?=$product->getProductTitle()?></h5>
		            <small><?=$product->getProductDescription()?></small>
		            <section class="price">
		                <p><strong><?=$product->getPrice()?></strong></p>
		            </section>
		            <p>Nombre : <select name="nbProducts[<?=$product->getProductId()?>]">
							        <option>---</option>
							        <option value="1">1</option>
							        <option value="2">2</option>
							        <option value="3">3</option>
							        <option value="4">4</option>
							        <option value="5">5</option>
							    </select></p>
		            </li>
        		<?php 
        			};
       			}
       			?>
    			</ul>
    		</section>
	</section>
</section>