<section class="delivery">
	<form>
		<h1>A emporter</h1>
		<section class="little-menu">
			<section class="food-delivery">
			    <h3>Entrées</h3>
			    <ul class="menu-delivery">
			        <li>
			            <img src="Public/img/menu/entree1.jpg" alt="entrée 1" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			        <li>
			            <img src="Public/img/menu/entree2.jpg" alt="entrée 2" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			        <li>
			            <img src="Public/img/menu/entree3.jpg" alt="entrée 3" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			    </ul>
			</section>

			<section class="food-delivery">
			    <h3>Plats</h3>
			    <ul class="menu-delivery">
			        <li>
			            <img src="Public/img/menu/plat1.jpg" alt="plat 1" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			        <li>
			            <img src="Public/img/menu/plat2.jpg" alt="plat 2" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			        <li>
			            <img src="Public/img/menu/plat3.jpg" alt="plat 3" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			        <li>
			            <img src="Public/img/menu/plat2.jpg" alt="plat 2" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			        <li>
			            <img src="Public/img/menu/plat2.jpg" alt="plat 2" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			            <p>Nombre : <select name="nbProducts">
					        <option>---</option>
					        <option value="1">1</option>
					        <option value="2">2</option>
					        <option value="3">3</option>
					        <option value="4">4</option>
					        <option value="5">5</option>
					    </select></p>
					    <button>Acheter</button>
			        </li>
			    </ul>
			</section>

			<section class="food-delivery">
			    <h3>Dessert</h3>
			    <ul class="menu-delivery">
			        <li>
			            <img src="Public/img/menu/dessert1.jpg" alt="dessert 1" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			        <li>
			            <img src="Public/img/menu/dessert2.jpg" alt="dessert 2" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			        <li>
			            <img src="Public/img/menu/dessert3.jpg" alt="dessert 3" />
			            <h5>Lorem ipsum dolor sit amet</h5>
			            <section class="price">
			                <p><strong>9,00€</strong></p>
			            </section>
			        </li>
			    </ul>
			</section>
		</section>
	</form>
</section>