<section class="delivery">
	<h1>A emporter</h1>
	<section class="little-menu">
		<section class="food">
        	<ul class="menu entre">
    			<h3>Entrées</h3>
			    <?php 
			    foreach ($products as $product) {
			        if(($product->getType())=="entre")
			        { 
			    ?>
   				<ul>
		            <li>
		                <img src="<?=$product->getPicture()?>">
		            <h5><?=$product->getProductTitle()?></h5>
		            <small><?=$product->getProductDescription()?></small>
		            <section class="price">
		                <p><strong><?=$product->getPrice()?></strong></p>
		            </section>
		            <p>Nombre : <select name="nbProducts">
							        <option>---</option>
							        <option value="1">1</option>
							        <option value="2">2</option>
							        <option value="3">3</option>
							        <option value="4">4</option>
							        <option value="5">5</option>
							    </select></p>
							    <button>Acheter</button>
		            </li>
				</ul>
        		<?php 
        			};
       			}
       			?>
    		</ul>

    		<ul class="menu plat">
    			<h3>Plats</h3>
			    <?php 
			    foreach ($products as $product) {
			        if(($product->getType())=="plat")
			        { 
			    ?>
   				<ul>
		            <li>
		                <img src="<?=$product->getPicture()?>">
		            <h5><?=$product->getProductTitle()?></h5>
		            <small><?=$product->getProductDescription()?></small>
		            <section class="price">
		                <p><strong><?=$product->getPrice()?></strong></p>
		            </section>
		            <p>Nombre : <select name="nbProducts">
							        <option>---</option>
							        <option value="1">1</option>
							        <option value="2">2</option>
							        <option value="3">3</option>
							        <option value="4">4</option>
							        <option value="5">5</option>
							    </select></p>
							    <button>Acheter</button>
		            </li>
				</ul>
        		<?php 
        			};
       			}
       			?>
    		</ul>

    		<ul class="menu dessert">
    			<h3>Desserts</h3>
			    <?php 
			    foreach ($products as $product) {
			        if(($product->getType())=="dessert")
			        { 
			    ?>
   				<ul>
		            <li>
		                <img src="<?=$product->getPicture()?>">
		            <h5><?=$product->getProductTitle()?></h5>
		            <small><?=$product->getProductDescription()?></small>
		            <section class="price">
		                <p><strong><?=$product->getPrice()?></strong></p>
		            </section>
		            <p>Nombre : <select name="nbProducts">
							        <option>---</option>
							        <option value="1">1</option>
							        <option value="2">2</option>
							        <option value="3">3</option>
							        <option value="4">4</option>
							        <option value="5">5</option>
							    </select></p>
							    <button>Acheter</button>
		            </li>
				</ul>
        		<?php 
        			};
       			}
       			?>
    		</ul>

    		<ul class="menu boisson">
    			<h3>Boissons</h3>
			    <?php 
			    foreach ($products as $product) {
			        if(($product->getType())=="boisson")
			        { 
			    ?>
   				<ul>
		            <li>
		                <img src="<?=$product->getPicture()?>">
		            <h5><?=$product->getProductTitle()?></h5>
		            <small><?=$product->getProductDescription()?></small>
		            <section class="price">
		                <p><strong><?=$product->getPrice()?></strong></p>
		            </section>
		            <p>Nombre : <select name="nbProducts">
							        <option>---</option>
							        <option value="1">1</option>
							        <option value="2">2</option>
							        <option value="3">3</option>
							        <option value="4">4</option>
							        <option value="5">5</option>
							    </select></p>
							    <button>Acheter</button>
		            </li>
				</ul>
        		<?php 
        			};
       			}
       			?>
    		</ul>
		</section>
	</section>
</section>