<section class="editmenu">

    <section class="food">


        <ul class="menu entre">
            <h3>Entrées</h3>
            <?php 
        foreach ($products as $product) {
        if(($product->getType())=="entre")
        { ?>
            <ul>
                <li>
                    <img src="<?=$product->getPicture()?>">
                    <h5><?=$product->getProductTitle()?></h5>
                    <small><?=$product->getProductDescription()?></small>
                    <section class="price">
                        <p><strong><?=$product->getPrice()?></strong></p>
                    </section>
                    <div><input class="edition" type="submit" value="Modifier"></div>
                </li>
            </ul>
            <?php };
        }?>
        </ul>



        <ul class="menu plat">
            <h3>Plat</h3>
            <?php 
        foreach ($products as $product) {
        if(($product->getType())=="plat")
        { ?>
            <ul>
                <li>
                    <img src="<?=$product->getPicture()?>">
                    <h5><?=$product->getProductTitle()?></h5>
                    <small><?=$product->getProductDescription()?></small>
                    <section class="price">
                        <p><strong><?=$product->getPrice()?></strong></p>
                    </section>
                    <div><input class="edition" type="submit" value="Modifier"></div>
                </li>
            </ul>
            <?php };
        }?>
        </ul>



        <ul class="menu dessert">
            <h3>Dessert</h3>
            <?php 
        foreach ($products as $product) {
        if(($product->getType())=="dessert")
        { ?>
            <ul>
                <li>
                    <img src="<?=$product->getPicture()?>">
                    <h5><?=$product->getProductTitle()?></h5>
                    <small><?=$product->getProductDescription()?></small>
                    <section class="price">
                        <p><strong><?=$product->getPrice()?></strong></p>
                    </section>
                    <div><input class="edition" type="submit" value="Modifier"></div>
                </li>
            </ul>
            <?php };
        }?>
        </ul>



        <ul class="menu boisson">
            <h3>Boissons</h3>
            <?php 
        foreach ($products as $product) {
        if(($product->getType())=="boisson")
        { ?>
            <ul>
                <li>
                    <img src="<?=$product->getPicture()?>">
                    <h5><?=$product->getProductTitle()?></h5>
                    <small><?=$product->getProductDescription()?></small>
                    <section class="price">
                        <p><strong><?=$product->getPrice()?></strong></p>
                    </section>
                    <div><input class="edition" type="submit" value="Modifier"></div>
                </li>
            </ul>
            <?php };
        }?>
        </ul>
    </section>
</section>



<h4>Edition menu</h4>

<form method="POST">
    <input type="hidden" name="action" value="create">
    <div>
        <p>Nom du produit :<input style="padding-left:10px" type="text" name="title" placeholder="Titre"></p>
    </div><br>
    <div>
        <p>Description :<textarea name="content" placeholder="Contenu"></textarea></p>
    </div><br>
    <div>
        <p>Image :<input style="padding-left:10px" type="url" name="image" placeholder="Url de l'image"></p>
    </div><br>
    <div>
        <p>Prix :<input style="padding-left:10px" type="url" name="image" placeholder="Url de l'image"></p>
    </div><br>
    <div>
        <p><input class="edition" type="submit" value="Créer Produit"></p>
    </div>
</form>


