<h4>Édition menu</h4>

<form method="POST">
    <input type="hidden" name="action" value="product.edit">
    <input type="hidden" name="product_id" value="<?=$product->getProductId()?>">
    <div> 
        <p>Nom du produit :<input style="padding-left:10px" type="text" name="product_title" 
        value="<?=$product->getProductTitle()?>" placeholder="Titre"></p>
    </div><br>
    <div>
        <p>Description :<textarea name="product_description" placeholder="Contenu"><?=$product->getProductDescription()?></textarea></p>
    </div><br>
    <div>
        <p>Image :<input style="padding-left:10px" type="file" name="picture" value="">
        <img src="<?=$product->getPicture()?>"></p>
    </div><br>
    <div>
        <p>Prix :<input style="padding-left:10px" type="text" name="price" value="<?=$product->getPrice()?>"></p>
    </div><br>
    <div>
        <p>Entrée : <input type="radio" name="type" value="entre" <?=$product->getType() == "entre" ? "checked" : "";?>></p>
        <p>Plat : <input type="radio" <?=$product->getType() == "plat" ? "checked" : "";?> name="type" value="plat"></p>
        <p>Dessert : <input type="radio" <?=$product->getType() == "dessert" ? "checked" : "";?> name="type" value="dessert"></p>
        <p>Boisson : <input <?=$product->getType() == "boisson" ? "checked" : "";?> type="radio" name="type" value="boisson"></p>
    </div>
    <div>
        <p><input class="edition" type="submit" value="Modifier Produit"></p>
    </div>
</form>


