<footer class="footer-user">

	<nav>
        <a href="?page=home">Home</a>
        <a href="?page=news">Actualités</a>
        <a href="?page=menu">Menu</a>
        <a href="?page=order">Commandes</a>
        <a href="?page=informations">Infos</a>
	</nav>

	<section>

		<address>Songohan<br> 15 rue des champs<br>67000 Strasbourg<br/>

		Téléphone : 03 88 25 24 98</address>


			
		<article>
			<i class="fab fa-facebook-square"></i>
				
		</article>
		<article>
			<i class="fab fa-twitter-square"></i>
					
		</article>
		<article>
			<i class="fab fa-instagram"></i>
					
		</article>

	</section>




	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2639.210774636216!2d7.674875316051282!3d48.58666297926163!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796b7b307fe3a91%3A0x4c2e83ab17dbce84!2sRue+des+Champs%2C+67201+Eckbolsheim!5e0!3m2!1sfr!2sfr!4v1519915250633" ></iframe>

	
</footer>