<footer class="footer-user">

	<a href="Accueil">Accueil</a>
	<a href="Accueil">Menu</a>
	<a href="Accueil">Commander</a>
	<a href="Accueil">Informations</a>


		<p>15 rue des champs 67000 STrasbourg <br/>

		Téléphone : 03 88 25 24 98</p>


			<section>
				<article>
					<i class="fab fa-facebook-square"></i>
				
				</article>
				<article>
					<i class="fab fa-twitter-square"></i>
					
				</article>
				<article>
					<i class="fab fa-instagram"></i>
					
				</article>

			</section>




<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2639.210774636216!2d7.674875316051282!3d48.58666297926163!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796b7b307fe3a91%3A0x4c2e83ab17dbce84!2sRue+des+Champs%2C+67201+Eckbolsheim!5e0!3m2!1sfr!2sfr!4v1519915250633" width="250" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>

	
</footer>