<header class="header-admin">
    <a href="#"><img id="logo" src="Public/img/logo.png" alt="logo Songohan" /></a>

    <nav>
        <a href="?page=creatarticle">Création d'article</a>
        <a href="?page=listearticle">Liste d'articles</a>
        <a href="?page=orders">Commandes</a>
        <a href="?page=modifymenu">Modif Menu</a>
        <a href="?page=resadetail">Réservations</a>
    </nav>

</header>
