
<section class="information">

	<img src="../Public/img/logo.png"></img>
	<h1>Présentation</h1>

		<p>Situé en plein cœur de Strasbourg, le Songohan restaurant au concept novateur et à la décoration contemporaine, réinvente la dégustation du sushi.

		« Le sushi n’est pas qu’un assemblage de poisson et de riz. Il nécessite des compétences et une dextérité acquises au prix de nombreuses années d’apprentissage. Trois générations de restaurateurs ont précédé Masami et l’on initié dés le plus jeune âge à l’art de la découpe du poisson, de la mise en scène des couleurs et du dressage des sushis. Son but aujourd’hui est de promouvoir le sushi et de l’élever en tant qu’art à part entière de la tradition culinaire japonaise. »</p>

</br>
		<h2>Horaires d'ouvertures</h2>

		<ul>
			<li>Mardi 11h00 à 23h00</li>
			<li>Mercredi 11h00 à 23h00</li>
			<li>Jeudi 11h00 à 23h00</li>
			<li>Vendredi 11h00 à 23h00</li>
			<li>Lundi 11h00 à 23h00</li>

		</ul>



		<div>
			<p>Adresse : 15 rue des champs</p>
			<p> 67000 STrasbourg</p>
			<p>Téléphone: 03 88 69 77 55</p>
			<a href="mailto:songohan@songohan.fr">songohan@songohan.fr</a>

		</div>
	
</section>