
<section id="information">

	

	<h1>Présentation</h1>

		<p>Situé en plein cœur de Strasbourg, le <span>Songohan</span> restaurant au concept novateur et à la décoration contemporaine, réinvente la dégustation du sushi.

		« Le sushi n’est pas qu’un assemblage de poisson et de riz. Il nécessite des compétences et une dextérité acquises au prix de nombreuses années d’apprentissage. Trois générations de restaurateurs ont précédé Masami et l’on initié dés le plus jeune âge à l’art de la découpe du poisson, de la mise en scène des couleurs et du dressage des sushis. Son but aujourd’hui est de promouvoir le sushi et de l’élever en tant qu’art à part entière de la tradition culinaire japonaise. »</p>


	

		<div>

			<h2>Horaires d'ouvertures</h2>

			<p>Du Mardi au Samedi de 11 h à 14 h et de 18 h à 23 h </p>

			<adress>Adresse : 15 rue des champs<br>
			67000 STrasbourg<br>
			Téléphone: 03 88 69 77 55<br>
			<a href="mailto:songohan@songohan.fr">songohan@songohan.fr</a></adress>



		
			<section>
				<article>
					<i class="fab fa-facebook-square"></i>
					<p>Facebook</p>
				</article>
				<article>
					<i class="fab fa-twitter-square"></i>
					<p>Twitter</p>
				</article>
				<article>
					<i class="fab fa-instagram"></i>
					<p>Instagram</p>
				</article>

			</section>



		</div>



	
</section>