<section class="login">
    <form method='POST'>
        <input type="hidden" name="action" value="login">
        <input type="hidden" name="group" value="user">
        <p>Login : <input type="text" name="username" placeholder="Login"></p>
        <p>Password : <input type="password" name="password" placeholder="Password"></p>
        <p><button type="submit" name="submit">Se connecter</button></p>
    </form>
</section>
