<section class="liste-menu">
    <section class="food">
        <h3>Entrées</h3>
        <ul class="menu">
            <li>
                <img src="Public/img/menu/entree1.jpg" alt="entrée 1" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
            <li>
                <img src="Public/img/menu/entree2.jpg" alt="entrée 2" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
            <li>
                <img src="Public/img/menu/entree3.jpg" alt="entrée 3" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
        </ul>
    </section>

    <section class="food">
        <h3>Plats</h3>
        <ul class="menu">
            <li>
                <img src="Public/img/menu/plat1.jpg" alt="plat 1" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
            <li>
                <img src="Public/img/menu/plat2.jpg" alt="plat 2" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
            <li>
                <img src="Public/img/menu/plat3.jpg" alt="plat 3" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
             <li>
                <img src="Public/img/menu/plat2.jpg" alt="plat 2" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
             <li>
                <img src="Public/img/menu/plat2.jpg" alt="plat 2" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
        </ul>
    </section>

    <section class="food">
        <h3>Dessert</h3>
        <ul class="menu">
            <li>
                <img src="Public/img/menu/dessert1.jpg" alt="dessert 1" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
            <li>
                <img src="Public/img/menu/dessert2.jpg" alt="dessert 2" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
            <li>
                <img src="Public/img/menu/dessert3.jpg" alt="dessert 3" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
        </ul>
    </section>


    <section class="food">
        <h3>Boissons</h3>
        <ul class="menu">
            <li>
                <img src="Public/img/menu/boisson.jpg" alt="boisson" />
                <h5>Lorem ipsum dolor sit amet</h5>
                <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam id ut necessitatibus eos eligendi voluptates, modi animi officia aspernatur quasi ratione facere sapiente quod provident, minima non rerum cumque adipisci.</small>
                <section class="price">
                    <p><strong>9,00€</strong></p>
                </section>
            </li>
        </ul>
    </section>
</section>