<section class="liste-menu">
    <section class="food">
        
        
    <ul class="menu entre">
    <h3>Entrées</h3>
    <?php 
    foreach ($products as $product) {
         if(($product->getType())=="entre")
        { ?>
    <ul>
            <li>
                <img src="<?=$product->getPicture()?>">
            <h5><?=$product->getProductTitle()?></h5>
            <small><?=$product->getProductDescription()?></small>
            <section class="price">
                <p><strong><?=$product->getPrice()?></strong></p>
            </section>
            </li>
</ul>
        <?php };
        }?>
    </ul>

    <ul class="menu plat">
    <h3>Plat</h3>
    <?php 
    foreach ($products as $product) {
         if(($product->getType())=="plat")
        { ?>
 <ul>
            <li>
                <img src="<?=$product->getPicture()?>">
            <h5><?=$product->getProductTitle()?></h5>
            <small><?=$product->getProductDescription()?></small>
            <section class="price">
                <p><strong><?=$product->getPrice()?></strong></p>
            </section>
            </li>
</ul>
        <?php };
        }?>
    </ul>

    <ul class="menu dessert">
    <h3>Dessert</h3>
    <?php 
    foreach ($products as $product) {
         if(($product->getType())=="dessert")
        { ?>
        <ul>
            <li>
                <img src="<?=$product->getPicture()?>">
            <h5><?=$product->getProductTitle()?></h5>
            <small><?=$product->getProductDescription()?></small>
            <section class="price">
                <p><strong><?=$product->getPrice()?></strong></p>
            </section>
            </li>
        </ul>
        <?php };
        }?>
    </ul>

    <ul class="menu boisson">
    <h3>Boissons</h3>
    <?php 
    foreach ($products as $product) {
         if(($product->getType())=="boisson")
        { ?>
         <ul>
            <li>
                <img src="<?=$product->getPicture()?>">
            <h5><?=$product->getProductTitle()?></h5>
            <small><?=$product->getProductDescription()?></small>
            <section class="price">
                <p><strong><?=$product->getPrice()?></strong></p>
            </section>
            </li>
        </ul>
        <?php };
        }?>
    </ul>



        



    </section>
 </section>