<form method="post">
<input type="hidden" name="action" value="" id="js_action">
<section class='order'>
	<section class="choix-menu">
			<h1>Commandez !</h1>
                <section id="choix-menu">
	</section>
		
	
		<p>Nom : <input type="text" name="firstName"></p>
		<p>Prénom : <input type="text" name="lastName"></p>
		<p>Email : <input type="email" name="email"></p>
		<p>Téléphone : <input type="text" name="phone"></p>
		<p>Adresse : <input type="text" name="address"></p>
		<p>Ville : <input type="text" name="city"></p>
		<p>Code postal : <input type="text" name="postalCode"></p>
		
		

</section>
<p id="choice">Sur place <input type="radio" name="choice" value="spot" class="radiospot"> - <input type="radio" name="choice" value="delivery" class="radiodel"> A emporter</p>
	<section class="spotview hidden">
		<?php
			require('Apps/spot.php');
		?>
	</section>
	<section class="deliveryview hidden">
		<?php
			require('Apps/delivery.php');
		?>
	</section>
<p><input class="boutton" type="submit" name="submit" value="Valider la commande"></p>
    </section> </form> 
