<section class='order'>
	<section class="choix-menu">
		<h1>Commandez !</h1>
	</section>
	<form method="post">
		<p>Nom : <input type="text" name="firstName"></p>
		<p>Prénom : <input type="text" name="lastName"></p>
		<p>Téléphone : <input type="text" name="phone"></p>
		<p>Adresse : <input type="text" name="address"></p>
		<p>Ville : <input type="text" name="city"></p>
		<p>Code postal : <input type="text" name="postalCode"></p>
		<p>Email : <input type="text" name="email"></p>
		
	</form>
</section>
<?php
// if () 
// {
// 	require('Apps/spot.php');
// }
// else
// {
// 	require('Apps/delivery.php');
// }