<section class="spot">
	<h2>Sur place</h2>
	<form method="POST">
		<p>Date de réservation : <input type="date" name="date"></p>
		<p>Horaire : <input type="button" name="11:30" Value="11:30" class="btn"><input type="button" name="12" Value="12:00" class="btn"><input type="button" name="12:30" Value="12:30" class="btn"><input type="button" name="13" Value="13:00" class="btn"><input type="button" name="13:30" Value="13:30" class="btn"><input type="button" name="14" Value="14:00" class="btn">
		<p><input type="button" name="19:30" Value="19:30" class="btn"><input type="button" name="20" Value="20:00" class="btn"><input type="button" name="20:30" Value="20:30" class="btn"><input type="button" name="21" Value="21:00" class="btn"><input type="button" name="21:30" Value="21:30" class="btn"><input type="button" name="22" Value="22:00" class="btn"></p></p>
		<p>Nombre de personnes : <select name="nbClient">
        <option>---</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
    </select></p>
	</form>

</section>