<section class="spot">
	<h2>Sur place</h2>
		<p>Date de réservation : <input type="date" name="date"></p>
		<p>Horaire : 
            <select name="hour">
                <optgroup label="Midi">
                    <option>11:30</option>
                    <option>12:00</option>
                    <option>12:30</option>
                    <option>13:00</option>
                    <option>13:30</option>
                    <option>14:00</option>
                </optgroup>
                <optgroup label="Soir">
                    <option>19:30</option>
                    <option>20:00</option>
                    <option>20:30</option>
                    <option>21:00</option>
                    <option>21:30</option>
                    <option>22:00</option>
                </optgroup>
            </select>
        </p>
		<p>Nombre de personnes : <select name="nbClient">
        <option>---</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
    </select></p>

</section>