<section class="spot">
	<h2>Sur place</h2>
	<form method="POST">
		<p>Date de réservation : <input type="date" name="date"></p>
		<p>Horaire : <input type="button" name="18" Value="18:00" class="btn"><input type="button" name="18:30" Value="18:30" class="btn"><input type="button" name="19" Value="19:00" class="btn"><input type="button" name="19:30" Value="19:30" class="btn"></p>
	</form>

</section>